spring:
  application:
    name: flight-on-time-backend
  
  web:
    cors:
      allowed-origins:
        - "http://localhost:4200"
        - "http://localhost:3000"
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS
      allowed-headers: "*"
      max-age: 3600
  
  # ===== DATABASE POSTGRESQL (DESARROLLO LOCAL) =====
  datasource:
    url: jdbc:postgresql://localhost:5432/vuelos
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080

# Data Science API
datascience:
  api:
    url: https://flightdelaypredictor-api.onrender.com