spring:
  application:
    name: flight-on-time-backend
  web:
    cors:
      allowed-origins:
        - "http://localhost:4200"
        - "http://localhost:3000"
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS
      allowed-headers: "*"
      max-age: 3600

server:
  port: 8080

# Data Science API
datascience:
  api:
    url: https://flightdelaypredictor-api.onrender.com